
# Site settings
title: Kamrun's Blog
description: A starter site
baseurl: "/Blog" # folder where your site lives, e.g. /web1-sp - needs to start with a slash
url: "http://ksamadnejad.github.io" # the base hostname & protocol for your site, e.g. http://hostname.domain.com

# Build settings
markdown: kramdown

defaults:  
  # template for pages unless an alternative is specified
  - scope:
      path: ""
    values:
      layout: "default"
